name: jupyterlab
channels:
  - rdkit
  - openbabel
  - bioconda
  - <unknown>
  - ambermd
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37hc8dfbb8_1
  - ambertools=19.0=0
  - asn1crypto=1.3.0=py37_0
  - astor=0.7.1=py_0
  - attrs=19.3.0=py_0
  - aws-parallelcluster=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - billiard=3.6.3.0=py37h7b6447c_0
  - biopython=1.76=py37h7b6447c_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - blosc=1.18.1=he1b5a44_0
  - boto3=1.12.39=py_0
  - botocore=1.15.39=pyh9f0ad1d_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.1=pyh8c360ce_0
  - cloudpickle=0.7.0=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h516909a_0
  - dalphaball=0.1.0=h14c3975_0
  - dask=2.11.0=py_0
  - dask-core=2.11.0=py_0
  - dask-jobqueue=0.7.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.11.0=py37_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.9=h516909a_0
  - fsspec=0.7.2=py_0
  - future=0.18.2=py37hc8dfbb8_1
  - gast=0.2.2=py_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.1=py_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.23.0=py37hb0870dc_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py37h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - heapdict=1.0.1=py_0
  - hhsuite=3.2.0=py37pl526he1b5a44_0
  - icu=58.2=h9c2bf20_1
  - idna=2.9=py_1
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py37_1
  - jinja2=2.11.1=py_0
  - jmespath=0.9.5=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.4=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.2=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.0=py_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=he6b73bb_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvm-openmp=8.0.1=hc9558a2_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.1.2=h14c3975_0
  - markdown=3.2.1=py_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - nb_conda_kernels=2.2.3=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py_0
  - openbabel=2.4.1=py37_6
  - openmp=8.0.1=0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.2.0=py_0
  - packaging=20.1=py_0
  - pandas=1.0.3=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h049681c_0
  - parso=0.6.2=py_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h516909a_1006
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - protobuf=3.11.4=py37h3340039_1
  - psutil=5.7.0=py37h8f50634_1
  - ptyprocess=0.6.0=py37_0
  - py-boost=1.67.0=py37h04863e7_4
  - py3dmol=0.8.0=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrosetta=2020.15+release.3121c73=py37_0
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h0371630_0
  - python-blosc=1.8.3=py37hb3f55d8_0
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.13=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.2=py_0
  - qtpy=1.9.0=py_0
  - rdkit=2020.03.1.0=py37hc20afe1_1
  - readline=7.0=h7b6447c_5
  - requests=2.23.0=py37_0
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.11.1=py37h8f50634_1
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tblib=1.6.0=py_0
  - tensorboard=1.15.0=py37_0
  - tensorflow=1.15.0=mkl_py37h28c19af_0
  - tensorflow-base=1.15.0=mkl_py37he1670d9_0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typing_extensions=3.7.4.1=py37hc8dfbb8_3
  - uncertainties=3.1.2=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h8f50634_1
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.3=h516909a_0
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attr==0.3.1
    - bokeh==1.4.0
    - dask-labextension==2.0.1
    - idisplay==0.1.2
    - isoelectric==1.0
    - jupyter-server-proxy==1.3.0
    - mmpbsa-py==16.0
    - multidict==4.7.5
    - packmol-memgen==1.0.5rc0
    - parmed==3.2.0
    - pdb4amber==1.7.dev0
    - peepdis==0.1.13
    - pymsmt==19.0
    - pyrosettacluster==0.6.1
    - pytraj==2.0.5
    - sander==16.0
    - simpervisor==0.3
    - yarl==1.4.2

